---

# Graphite db init
- name: inspect graphite db
  command: graphite-manage inspectdb
  register: graphite_inspect
  changed_when: False

- name: check for secret key warning
  command: echo SECRET_KEY is set to an unsafe default.
  failed_when: "'SECRET_KEY' in graphite_inspect.stderr"
  changed_when: False

- name: check if superuser and db have already been deployed
  stat: path='/usr/share/graphite-web/.superuser_created'
  register: superuser_created

- name: create schema
  command: graphite-manage syncdb --noinput
  when: superuser_created.stat.exists == False

- name: create superuser account
  command: graphite-manage createsuperuser --username={{ graphite_admin_username }} --email={{ graphite_admin_email }} --noinput
  when: superuser_created.stat.exists == False

- name: set superuser password
  expect:
  command: /usr/bin/graphite-manage changepassword {{ graphite_admin_username }}
  responses:
    Password: {{ graphite_admin_password }}
    Password (again): {{ graphite_admin_password }}
  when: superuser_created.stat.exists == False

- name: create lock file
  file: path="/usr/share/graphite-web/.superuser_created" state=touch
  when: superuser_created.stat.exists == False

- meta: flush_handlers
