---

# Carbon
- name: deploy webapp configuration file
  template: src=local_settings.py.j2 dest=/etc/graphite/local_settings.py owner=root group=root mode=0644 backup=yes

- name: migrate django auth
  command: django-admin migrate --settings=graphite.settings auth
  notify: graphite syncdb

- meta: flush_handlers

- name: configure carbon to start at boot
  lineinfile: dest=/etc/default/graphite-carbon regexp="^CARBON_CACHE_ENABLED=" line='CARBON_CACHE_ENABLED=true'

- name: deploy carbon configuration file
  template: src=carbon.conf.j2 dest=/etc/carbon/carbon.conf mode=0644 owner=root group=root
  notify: carbon restart

- name: deploy storage schema configuration file
  template: src=storage-schemas.conf.j2 dest=/etc/carbon/storage-schemas.conf mode=0644 owner=root group=root
  notify: carbon restart

- name: deploy storage aggregation configuration file
  template: src=storage-aggregation.conf.j2 dest=/etc/carbon/storage-aggregation.conf mode=0644 owner=root group=root
  notify: carbon restart

- name: ensure carbon directories exist
  file: path={{item}} owner={{graphite_uid}} group={{graphite_gid}} follow=yes recurse=yes state=directory
  with_items:
    - "{{carbon_logdir}}"

- name: start carbon-cache
  service: name=carbon-cache state=restarted enabled=yes
  when: graphite_manage_service
