---

- name: install graphite packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - graphite-web
    - graphite-carbon
  register: graphite_packages

- name: remove database files when purging graphite-carbon
  debconf: name='graphite-carbon' question='Configuring graphite-carbon' value='no' vtype='string'
  when: graphite_packages|changed
  notify:
  - carbon stop

- meta: flush_handlers

- name: ensure graphite directories exist
  file: path={{item}} owner={{graphite_uid}} group={{graphite_gid}} follow=yes recurse=yes state=directory
  with_items:
    - "{{graphite_datadir}}"
    - "{{graphite_logdir}}"
    - "{{carbon_logdir}}"
    - "{{graphite_datadir}}/whisper"
    - "{{graphite_datadir}}/rrd"
    - "{{graphite_datadir}}/ceres"
    - "{{graphite_datadir}}/conf"

- name: reset graphite folder and subfolder to new uid
  file: path={{item}} owner={{graphite_uid}} group={{graphite_gid}} follow=yes recurse=yes state=directory
  with_items:
    - "{{graphite_datadir}}"
    - "{{graphite_logdir}}"
    - "{{carbon_logdir}}"
    - "{{graphite_datadir}}/whisper"
    - "{{graphite_datadir}}/rrd"
    - "{{graphite_datadir}}/ceres"
    - "{{graphite_datadir}}/conf"

- name: build the search index for graphite
  command: graphite-build-search-index

- name: start graphite carbon
  service: name=carbon-cache state=restarted
