---

# Install pacakges
- include: install.yml
  tags: [graphite]

# Carbon cache
- include: carbon.yml
  tags: [graphite, carbon-cache]

- include: carbon_db.yml
  when: graphite_manage_db
  tags: [graphite, carbon-cache, carbon-cache-db]

# Uwsgi
- include: uwsgi.yml
  when: graphite_manage_uwsgi
  tags: [graphite, uwsgi]

# Cleanup
- include: cleanup.yml
  tags: [graphite]